# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT" # Want to make your mod open source? Check out https://choosealicense.com/!

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
modId = "inventoryfix"
# The version number of the mod - unlike in the Forge MDK,
# we'll use the processResources task to replace this for us
version = "${version}"
displayName = "Inventory fix"
# This URL will be queried by the Forge update checker in order to find the latest version of your mod.
# If an update is found, you'll see a little blinking "emerald" symbol on your Mods button!
# updateJSONURL="https://changeme.dev/updates.json" #optional
# This is your mod's "homepage" and will be displayed on the mod's information screen in the Mods panel.
displayURL="https://kosmx.dev/" #optional
# This will be displayed as your mod's logo in the Mods panel.
# logoFile="icon.png" #optional
# Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
credits="FabricMC, Architectury" # So Forge devs won't touch this unholy shit :D
# Some more fluff displayed in the Mods panel. Plug your stuff here!
authors="KosmX" #optional
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = '''
Fuck forge

Lorem ipsum dolor sit amet sed eleifend et diam est tempor ut justo ut erat ea dolor voluptua dolore ut et invidunt ut nonummy accusam ea et lorem congue stet blandit aliquip dolores sanctus ipsum aliquyam no lorem et lorem labore laoreet dignissim kasd autem et no magna feugiat erat magna dolore sea et kasd stet elit invidunt eos eros at commodo at stet voluptua cum sea clita et duis est commodo tempor clita iriure voluptua ut clita
'''

# An (optional) dependency for your mod. Though technically not required,
# it's always helpful to add these to stop your mod from loading when something is missing
# rather than erroring out later
[[dependencies.inventoryfix]]
modId = "forge"
mandatory = true # do you **need** this mod to be able to launch?
# A version range using interval notation.
# Brackets mean "inclusive" bounds, while parentheses mean "exclusive".
versionRange = "[40,)" # This essentially means any forge >= @FORGE_LOADER_MAJOR@
ordering = "NONE" # Use this if you want your mod to be loaded specifically BEFORE or AFTER another mod
side = "CLIENT" # Specify where this mod is required: can be BOTH, CLIENT or SERVER

# And another dependency, use this if you want to require a certain Minecraft version.
[[dependencies.inventoryfix]]
modId = "minecraft"
mandatory = true
# See above for how to read this notation, this essentially means any
# version of Minecraft from @MINECRAFT@ (inclusive).
versionRange = "[1.18,)"
ordering = "NONE"
side = "CLIENT"